package com.chronicle.newsfeed.ui.theme

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf

data class AppStrings(
    val appName: String,
    val appTagline: String,
    val dailyDigest: String,
    val dailyDigestDesc: String,
    val dailyDigestBtn: String,
    val customDigest: String,
    val customDigestDesc: String,
    val customBulletinBtn: String,
    val customBulletinHeader: String,
    val customBulletinGenerate: String,
    val customBulletinSelectPrompt: String,
    val queueStoryProgress: String,
    val cancel: String,
    val selectAll: String,
    val clearSelection: String,
    val listenArticle: String,
    val narrating: String,
    val generatingSummary: String,
    val playingAudio: String,
    val loadingModels: String,
    val modelsReady: String,
    val searchPlaceholder: String,
    val filterAll: String,
    val filterUnread: String,
    val filterFavorites: String,
    val filters: String,
    val markAllRead: String,
    val activeFilters: String,
    val clear: String,
    val emptyFeedTitle: String,
    val emptyFeedSubtitle: String,
    val sources: String,
    val settings: String,
    val pause: String,
    val resume: String,
    val close: String,
    val openOriginal: String,
    val favorite: String,
    val markAsRead: String,
    val sortByRecent: String,
    val sortBySource: String,
    val generatingCustomDigest: String,
    val storiesSelectedCount: String,
    val analyzeStoriesCount: String
)

val StringsEs = AppStrings(
    appName = "CHRONICLE",
    appTagline = "Lector Editorial & Locutor de IA",
    dailyDigest = "Boletín de Noticias de Hoy",
    dailyDigestDesc = "Informativo radiofónico sintetizado por IA con las noticias clave de la jornada.",
    dailyDigestBtn = "Noticias de hoy",
    customDigest = "Boletín Personalizado",
    customDigestDesc = "Informativo exclusivo generado con las noticias que tú elijas.",
    customBulletinBtn = "Seleccionar noticias",
    customBulletinHeader = "Seleccionar noticias",
    customBulletinGenerate = "Escuchar",
    customBulletinSelectPrompt = "Toca las noticias que desees escuchar",
    queueStoryProgress = "Noticia %d de %d",
    cancel = "Cancelar",
    selectAll = "Seleccionar todo",
    clearSelection = "Limpiar selección",
    listenArticle = "Escuchar artículo",
    narrating = "Locutando…",
    generatingSummary = "Generando resumen hablado con Gemma…",
    playingAudio = "Reproduciendo locución…",
    loadingModels = "Iniciando motor de IA y voces…",
    modelsReady = "Motor de IA y síntesis de voz listos",
    searchPlaceholder = "Buscar en titulares o fuentes…",
    filterAll = "Todos",
    filterUnread = "No leídos",
    filterFavorites = "Favoritos",
    filters = "Filtros",
    markAllRead = "Marcar todo leído",
    activeFilters = "Activos:",
    clear = "Limpiar",
    emptyFeedTitle = "No hay noticias con los filtros actuales.",
    emptyFeedSubtitle = "Prueba a refrescar o a reiniciar los filtros.",
    sources = "Fuentes",
    settings = "Ajustes",
    pause = "Pausar",
    resume = "Reanudar",
    close = "Cerrar",
    openOriginal = "Abrir enlace original",
    favorite = "Favorito",
    markAsRead = "Marcar leído",
    sortByRecent = "Recientes",
    sortBySource = "Por fuente",
    generatingCustomDigest = "Gemma está sintetizando tu selección de noticias…",
    storiesSelectedCount = "%d seleccionadas",
    analyzeStoriesCount = "Sintetizadas %d historias seleccionadas"
)

val StringsEn = AppStrings(
    appName = "CHRONICLE",
    appTagline = "Editorial News & Local AI Broadcaster",
    dailyDigest = "Today's News Bulletin",
    dailyDigestDesc = "AI-synthesized radio news bulletin featuring today's key stories.",
    dailyDigestBtn = "Today's news",
    customDigest = "Custom News Bulletin",
    customDigestDesc = "Exclusive spoken briefing synthesized from the stories you select.",
    customBulletinBtn = "Select stories",
    customBulletinHeader = "Select stories",
    customBulletinGenerate = "Listen",
    customBulletinSelectPrompt = "Tap the stories you want to listen to",
    queueStoryProgress = "Story %d of %d",
    cancel = "Cancel",
    selectAll = "Select all",
    clearSelection = "Clear selection",
    listenArticle = "Listen article",
    narrating = "Narrating…",
    generatingSummary = "Generating spoken summary with Gemma…",
    playingAudio = "Playing narration…",
    loadingModels = "Loading AI model & voices…",
    modelsReady = "AI model and voices ready",
    searchPlaceholder = "Search in headlines or sources…",
    filterAll = "All",
    filterUnread = "Unread",
    filterFavorites = "Favorites",
    filters = "Filters",
    markAllRead = "Mark all read",
    activeFilters = "Active:",
    clear = "Clear",
    emptyFeedTitle = "No stories found with the current filters.",
    emptyFeedSubtitle = "Try refreshing or resetting your filters.",
    sources = "Sources",
    settings = "Settings",
    pause = "Pause",
    resume = "Resume",
    close = "Close",
    openOriginal = "Open original link",
    favorite = "Favorite",
    markAsRead = "Mark read",
    sortByRecent = "Recent",
    sortBySource = "By source",
    generatingCustomDigest = "Gemma is synthesizing your custom bulletin…",
    storiesSelectedCount = "%d selected",
    analyzeStoriesCount = "Synthesized %d selected stories"
)

val LocalAppStrings = compositionLocalOf { StringsEs }

fun getAppStrings(language: String): AppStrings {
    return if (language.equals("en", ignoreCase = true)) StringsEn else StringsEs
}
